-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
--
-- local typescript_group = vim.api.nvim_create_augroup("TypeScript Stuff", { clear = true })
--
-- vim.api.nvim_create_autocmd({
--   "BufWritePre",
--   command = ""
-- })
